/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIdRouteImport } from './routes/questions.$id'

const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdRoute = QuestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spark': typeof SparkRoute
  '/questions/$id': typeof QuestionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spark': typeof SparkRoute
  '/questions/$id': typeof QuestionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spark': typeof SparkRoute
  '/questions/$id': typeof QuestionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/insights'
    | '/login'
    | '/questions'
    | '/settings'
    | '/spark'
    | '/questions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/insights'
    | '/login'
    | '/questions'
    | '/settings'
    | '/spark'
    | '/questions/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/insights'
    | '/login'
    | '/questions'
    | '/settings'
    | '/spark'
    | '/questions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  QuestionsRoute: typeof QuestionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SparkRoute: typeof SparkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id': {
      id: '/questions/$id'
      path: '/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdRouteImport
      parentRoute: typeof QuestionsRoute
    }
  }
}

interface QuestionsRouteChildren {
  QuestionsIdRoute: typeof QuestionsIdRoute
}

const QuestionsRouteChildren: QuestionsRouteChildren = {
  QuestionsIdRoute: QuestionsIdRoute,
}

const QuestionsRouteWithChildren = QuestionsRoute._addFileChildren(
  QuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  QuestionsRoute: QuestionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SparkRoute: SparkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
